### ISSUE TITLE
HW2

### ISSUE THREAD

**Issue by GuillaumeDonnet** [CitronPerfide/Applied_Statistics_with_R#2]

**Comment by AntonZamyatin** [comment]
You have a large overhead in counting chances.
1. You need no to use FOR cycles in R when you want to iterate with some function over any object.
For example `sum()` function can summarize whole numeric vector in one line of code. You could try to find its inner implementation and of course you will find FOR cycle inside but this cycle is optimised for your comfort.
2. Please divide you functions into smaller atomic action pieces. Think about them like a verb in natural language (what you want this function to do)
3. I don't like you chances calculation at all. You create a lot of new variables like distances and so on. But you can just count how many cards in deck are sutisfy conditions if we add them to player sum.
So I think you must work on this HW a bit more.

**Comment by AntonZamyatin** [comment]
Ok.Done
